name: Go CGO Auto Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'

      - name: Build CGO binary
        uses: go-cross/cgo-actions@v1.1.0
        with:
          dir: .
          packages: .
          flags: "-ldflags=-w -s"
          out-dir: bin
          x-flags: ""
          targets: linux/amd64,windows/amd64,darwin/arm64

      - name: Package binaries
        run: |
          for file in bin/*; do
            zip -j "${file}.zip" "$file"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: bin/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
