name: Go CGO Auto Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'

      - name: Build CGO binary
        uses: go-cross/cgo-actions@v1.1.0
        with:
          dir: .
          packages: .
          flags: "-ldflags=-w -s"
          out-dir: bin
          output: whapi
          x-flags: ""

      - name: Zip binary
        run: zip -j whapi.zip bin/whapi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: whapi.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
